services:
  - type: web
    name: controle-tempo
    runtime: docker
    plan: free
    region: ohio
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /up
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: Controle de Horas
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_LOCALE
        value: pt_BR
      - key: APP_FALLBACK_LOCALE
        value: pt_BR
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: ADMIN_NAME
        value: Administrador
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: "10000"
