<form method="GET" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
    <label class="text-xs font-semibold text-slate-600">Data inicial<input type="date" name="date_from" value="{{ request('date_from') }}" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label>
    <label class="text-xs font-semibold text-slate-600">Data final<input type="date" name="date_to" value="{{ request('date_to') }}" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label>
    @if(auth()->user()->isManagerOrAdmin())<label class="text-xs font-semibold text-slate-600">Usuário<select name="user_id" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="">Todos</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(request('user_id')==$user->id)>{{ $user->name }}</option>@endforeach</select></label>@endif
    <label class="text-xs font-semibold text-slate-600">Cliente<select name="client_id" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="">Todos</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(request('client_id')==$client->id)>{{ $client->name }}</option>@endforeach</select></label>
    <label class="text-xs font-semibold text-slate-600">Projeto<select name="project_id" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="">Todos</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected(request('project_id')==$project->id)>{{ $project->name }}</option>@endforeach</select></label>
    <label class="text-xs font-semibold text-slate-600">Atividade<select name="activity_id" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="">Todas</option>@foreach($activities as $activity)<option value="{{ $activity->id }}" @selected(request('activity_id')==$activity->id)>{{ $activity->name }}</option>@endforeach</select></label>
    <label class="text-xs font-semibold text-slate-600">Tipo<select name="entry_type" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="">Todos</option><option value="timer" @selected(request('entry_type')==='timer')>Cronômetro</option><option value="manual" @selected(request('entry_type')==='manual')>Manual</option></select></label>
    <label class="text-xs font-semibold text-slate-600">Status<select name="status" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="">Todos</option>@foreach(\App\Enums\EntryStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select></label>
    <div class="flex items-end gap-2"><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Filtrar</button><a href="{{ url()->current() }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm">Limpar</a></div>
</form>
