@php $editing=isset($entry) && $entry->exists; @endphp
<div x-data="{client:'{{ old('client_id', $editing ? $entry->project->client_id : '') }}', projects:@js($projects->map(fn($p)=>['id'=>$p->id,'name'=>$p->name,'client_id'=>$p->client_id])->values())}" class="grid gap-5 md:grid-cols-2">
    @if(auth()->user()->isManagerOrAdmin() && !$editing)<label class="text-sm font-semibold">Usuário<select name="user_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">Eu mesmo</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('user_id')==$user->id)>{{ $user->name }}</option>@endforeach</select></label>@endif
    <label class="text-sm font-semibold">Cliente<select x-model="client" name="client_id" required class="mt-1 w-full rounded-xl border-slate-300"><option value="">Selecione</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold">Projeto<select name="project_id" required class="mt-1 w-full rounded-xl border-slate-300"><option value="">Selecione</option><template x-for="p in projects.filter(p=>String(p.client_id)===String(client))" :key="p.id"><option :value="p.id" x-text="p.name" :selected="String(p.id)===String('{{ old('project_id', $editing ? $entry->project_id : '') }}')"></option></template></select></label>
    <label class="text-sm font-semibold">Atividade<select name="activity_id" required class="mt-1 w-full rounded-xl border-slate-300"><option value="">Selecione</option>@foreach($activities as $activity)<option value="{{ $activity->id }}" @selected(old('activity_id',$editing?$entry->activity_id:null)==$activity->id)>{{ $activity->name }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold">Início<input type="datetime-local" name="started_at" required value="{{ old('started_at',$editing?$entry->started_at->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></label>
    <label class="text-sm font-semibold">Término<input type="datetime-local" name="ended_at" required value="{{ old('ended_at',$editing?$entry->ended_at?->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></label>
    <label class="text-sm font-semibold md:col-span-2">Descrição<textarea name="description" rows="3" maxlength="2000" class="mt-1 w-full rounded-xl border-slate-300">{{ old('description',$editing?$entry->description:'') }}</textarea></label>
    <label class="text-sm font-semibold md:col-span-2">Justificativa do lançamento {{ $editing ? '' : '*' }}<textarea name="justification" rows="3" maxlength="2000" @required(!$editing) class="mt-1 w-full rounded-xl border-slate-300">{{ old('justification',$editing?$entry->justification:'') }}</textarea></label>
</div>
