<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-cyan-700">Apontamentos</p><h1 class="text-2xl font-bold">Registros de horas</h1></div><div class="flex gap-2"><a href="{{ route('time-entries.export', request()->query()) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Exportar CSV</a><a href="{{ route('time-entries.create') }}" class="rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-bold text-slate-950">Adicionar horas</a></div></div></x-slot>
    @include('time-entries._filters')
    <div class="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full whitespace-nowrap text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4"><a href="{{ request()->fullUrlWithQuery(['sort'=>'started_at','direction'=>request('direction')==='asc'?'desc':'asc']) }}">Data/Início</a></th><th class="p-4">Usuário</th><th class="p-4">Cliente / Projeto</th><th class="p-4">Atividade</th><th class="p-4">Duração</th><th class="p-4">Tipo</th><th class="p-4">Status</th><th class="p-4">Ações</th></tr></thead><tbody>
        @forelse($entries as $entry)<tr class="border-t border-slate-100 hover:bg-slate-50"><td class="p-4"><strong>{{ $entry->started_at->format('d/m/Y') }}</strong><span class="block text-xs text-slate-500">{{ $entry->started_at->format('H:i') }} – {{ $entry->ended_at?->format('H:i') ?? 'agora' }}</span></td><td class="p-4">{{ $entry->user->name }}</td><td class="p-4"><span class="text-xs text-slate-500">{{ $entry->project->client->name }}</span><strong class="block">{{ $entry->project->name }}</strong></td><td class="p-4">{{ $entry->activity->name }}</td><td class="p-4 font-bold"><x-duration :seconds="$entry->duration_seconds" /></td><td class="p-4">{{ $entry->entry_type->label() }}@if($entry->is_edited)<span class="block text-xs text-amber-700">Editado</span>@endif</td><td class="p-4"><x-status-badge :status="$entry->status" /></td><td class="p-4"><div class="flex items-center gap-2"><a href="{{ route('time-entries.show',$entry) }}" class="font-semibold text-cyan-700">Ver</a>@can('update',$entry)<a href="{{ route('time-entries.edit',$entry) }}" class="font-semibold text-indigo-700">Editar</a>@endcan @can('delete',$entry)<form method="POST" action="{{ route('time-entries.destroy',$entry) }}" onsubmit="return confirm('Excluir este registro?')">@csrf @method('DELETE')<button class="font-semibold text-red-700">Excluir</button></form>@endcan</div>
            @can('approve',$entry) @if($entry->status===\App\Enums\EntryStatus::Pending)<div class="mt-2 flex gap-2"><form method="POST" action="{{ route('time-entries.approve',$entry) }}">@csrf @method('PATCH')<button class="rounded bg-emerald-100 px-2 py-1 text-xs font-semibold text-emerald-800">Aprovar</button></form><form method="POST" action="{{ route('time-entries.reject',$entry) }}" class="flex">@csrf @method('PATCH')<input name="rejection_reason" required placeholder="Motivo" class="w-28 rounded-l border-slate-300 py-1 text-xs"><button class="rounded-r bg-red-100 px-2 py-1 text-xs font-semibold text-red-800">Rejeitar</button></form></div>@endif @endcan
        </td></tr>@empty<tr><td colspan="8" class="p-10 text-center text-slate-500">Nenhum registro encontrado para os filtros selecionados.</td></tr>@endforelse
        </tbody></table></div><div class="border-t border-slate-100 p-4">{{ $entries->links() }}</div></div>
</x-app-layout>
